### ISSUE TITLE
Trigger a merged build per pipeline rather than step

### ISSUE THREAD

**Issue by zsims** [seek-oss/github-merged-pr-buildkite-plugin#6]
If the build pipeline has multiple steps, then multiple merge builds will be triggered. There should be only merged build triggered.

**Comment by flexportnes** [comment]
I'm interested in using this plugin over our home-grown solution, however we would need this functionality before switching. We currently pin the commit that will be merged into the PR as an artifact/metadata so that there's a consistent merge for all of the different steps, even if new commits are added to the target branch.

**Comment by zsims** [comment]
The plugin can do what's in this bug, it's just about avoiding duplicate builds on:

```
steps:
  - label: 'Make something'
    commands:
      - make something
    plugins:
      - seek-oss/github-merged-pr#v1.0.1:
          mode: trigger

  - label: 'Make something else'
    commands:
      - make something-else
    plugins:
      - seek-oss/github-merged-pr#v1.0.1:
          mode: trigger
```

The idea was to set metadata to make sure it's only triggered once. Regardless if you have multiple steps. Is that what you're after?
